export const VIEW_TRAIN_REQUEST = "VIEW_TRAIN_REQUEST";
export const VIEW_TRAIN_SUCCESS = "VIEW_TRAIN_SUCCESS";
export const VIEW_TRAIN_FAIL = "VIEW_TRAIN_FAIL";
  
export const NEW_TRAIN_REQUEST = "NEW_TRAIN_REQUEST";
export const NEW_TRAIN_SUCCESS = "NEW_TRAIN_SUCCESS";
export const NEW_TRAIN_FAIL = "NEW_TRAIN_FAIL";
export const NEW_TRAIN_RESET = "NEW_TRAIN_RESET";

export const UPDATE_TRAIN_REQUEST = "UPDATE_TRAIN_REQUEST";
export const UPDATE_TRAIN_SUCCESS = "UPDATE_TRAIN_SUCCESS";
export const UPDATE_TRAIN_FAIL = "UPDATE_TRAIN_FAIL";
export const UPDATE_TRAIN_RESET = "UPDATE_TRAIN_RESET";

export const DELETE_TRAIN_REQUEST = "DELETE_TRAIN_REQUEST";
export const DELETE_TRAIN_SUCCESS = "DELETE_TRAIN_SUCCESS"
export const DELETE_TRAIN_FAIL = "DELETE_TRAIN_FAIL";
export const DELETE_TRAIN_RESET = "DELETE_TRAIN_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";